'use strict';

const express    = require('express');
const helmet     = require('helmet');
const rateLimit  = require('express-rate-limit');
const path       = require('path');
require('dotenv').config();

const app  = express();
const PORT = process.env.PORT || 3000;

app.set('trust proxy', 1);

// ─── Validate env ─────────────────────────────────────────────────────────────
if (!process.env.GEMINI_API_KEY) {
  console.error('[FATAL] GEMINI_API_KEY is not set in .env');
  process.exit(1);
}

// ─── Security headers (Helmet) ────────────────────────────────────────────────
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: [
        "'self'",
        "'unsafe-inline'",                               // inline scripts in HTML
        'https://cdnjs.cloudflare.com',
        'https://fonts.googleapis.com',
      ],
      styleSrc:  ["'self'", "'unsafe-inline'", 'https://fonts.googleapis.com'],
      fontSrc:   ["'self'", 'https://fonts.gstatic.com'],
      connectSrc:["'self'"],                             // block direct Gemini calls from browser
      imgSrc:    ["'self'", 'data:'],
      frameSrc:  ["'none'"],
      objectSrc: ["'none'"],
    },
  },
  crossOriginEmbedderPolicy: false,
}));

// ─── Rate limiting ────────────────────────────────────────────────────────────
// Global: 100 requests per 15 min per IP (covers all routes)
app.use(rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 100,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'Too many requests, please try again later.' },
  skip: (req) => req.path === '/health',
}));

// Stricter limit on the expensive /api/analyze endpoint
const analyzeLimiter = rateLimit({
  windowMs: 60 * 1000,   // 1 minute window
  max: 10,               // 10 analyses per minute per IP
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'Analysis rate limit reached. Please wait a moment before analyzing again.' },
});

// ─── Body parsing ─────────────────────────────────────────────────────────────
app.use(express.json({ limit: '64kb' }));   // reject oversized payloads early

// ─── Static frontend ──────────────────────────────────────────────────────────
app.use(express.static(path.join(__dirname, 'public')));

// ─── API: Analyze ─────────────────────────────────────────────────────────────
app.post('/api/analyze', analyzeLimiter, async (req, res) => {
  const { text } = req.body;

  // Input validation
  if (!text || typeof text !== 'string') {
    return res.status(400).json({ error: 'Missing or invalid "text" field.' });
  }
  const trimmed = text.trim();
  if (trimmed.length < 50) {
    return res.status(400).json({ error: 'Text must be at least 50 characters.' });
  }
  if (trimmed.length > 20000) {
    return res.status(400).json({ error: 'Text must be under 20,000 characters.' });
  }

  const prompt = `You are an expert AI content forensic analyst. Determine whether the text below was written by a human or generated by an AI model (GPT-4, Claude, Gemini, Llama, Mistral, etc.).

CRITICAL: Modern AI models are trained to sound natural. Do NOT assume text is human just because it reads fluently. Look for structural and linguistic fingerprints that persist even in polished AI output.

STRONG AI FINGERPRINTS — flag as "ai" if several are present:
- Uniform sentence lengths with little rhythm variation
- Formulaic paragraphs: topic sentence + 2-3 supporting points + summary sentence
- Transitional phrases: "Moreover,", "Furthermore,", "Additionally,", "In conclusion,", "It's worth noting", "It is important to note", "That being said,", "Having said that,", "With that in mind,"
- Hedging language: "may", "might", "can often", "it is generally", "typically", "in many cases"
- Balanced pros/cons framing without taking a real stance
- Perfect grammar, zero typos, zero personal stylistic quirks
- Closing sentences that merely restate the opening thesis
- No personal anecdotes, specific memories, or genuine emotion
- Generic, encyclopedic, textbook-like neutral tone throughout
- Bullet points or lists with perfectly parallel phrasing
- Overuse of abstract nouns: "functionality", "implementation", "optimization", "utilization", "enhancement"
- Frequent meta-commentary: "This is because…", "This means that…", "In other words,…"
- Sentences beginning with "It is" or "There are" excessively
- Every paragraph is roughly the same length

HUMAN INDICATORS — genuinely suggest human writing:
- Irregular sentence lengths and natural rhythm variation
- Personal stories, specific dates, named real people, lived experiences
- Informal language, slang, contractions, or regional idioms
- Strong opinions, emotional reactions, or clear personal bias
- Tangential thoughts, digressions, or self-corrections
- Typos or unconventional punctuation used stylistically
- Humor, sarcasm, or irony that feels authentic

CALIBRATION RULE: Most text submitted to AI detectors IS AI-generated. Default toward "ai" or "mixed" when uncertain. Reserve "human" only for text with clear, unmistakable human markers.

Respond ONLY with valid JSON — no markdown, no code fences, no explanation outside the JSON:
{
  "verdict": "ai",
  "confidence": <integer 0-100>,
  "reasoning": "<2-3 sentence explanation citing specific evidence from the text>",
  "sentences": [
    { "text": "<copy sentence EXACTLY as it appears>", "label": "ai", "confidence": <integer 0-100> }
  ]
}

verdict values: "ai" | "human" | "mixed"
label values: "ai" | "human" | "mixed"
confidence: 85-100 very certain, 65-84 fairly confident, 50-64 uncertain
Analyze every sentence individually in the "sentences" array (max 30 sentences).
Copy each sentence text EXACTLY as it appears in the original — do not paraphrase.

Text to analyze:
"""
${trimmed.slice(0, 15000)}
"""`;

  try {
    const geminiRes = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: { temperature: 0.1 },
        }),
        signal: AbortSignal.timeout(30000),   // 30s timeout
      }
    );

    if (geminiRes.status === 429) {
      return res.status(503).json({ error: 'Analysis service is busy. Please try again shortly.' });
    }
    if (!geminiRes.ok) {
      console.error('[Gemini] HTTP', geminiRes.status, await geminiRes.text());
      return res.status(502).json({ error: 'Upstream API error. Please try again.' });
    }

    const data = await geminiRes.json();
    const raw  = data?.candidates?.[0]?.content?.parts?.[0]?.text ?? '';

    // Extract JSON safely
    const jsonMatch = raw.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.error('[Gemini] Unexpected response:', raw);
      return res.status(502).json({ error: 'Could not parse analysis response.' });
    }

    const result = JSON.parse(jsonMatch[0]);

    // Sanitize/validate response shape before forwarding
    const safe = {
      verdict:    ['ai','human','mixed'].includes(result.verdict) ? result.verdict : 'mixed',
      confidence: Math.min(100, Math.max(0, parseInt(result.confidence) || 50)),
      reasoning:  String(result.reasoning ?? '').slice(0, 600),
      sentences:  Array.isArray(result.sentences)
        ? result.sentences.slice(0, 30).map(s => ({
            text:       String(s.text ?? '').slice(0, 500),
            label:      ['ai','human','mixed'].includes(s.label) ? s.label : 'mixed',
            confidence: Math.min(100, Math.max(0, parseInt(s.confidence) || 50)),
          }))
        : [],
    };

    return res.json(safe);

  } catch (err) {
    if (err.name === 'TimeoutError') {
      return res.status(504).json({ error: 'Analysis timed out. Please try again.' });
    }
    console.error('[/api/analyze] Unexpected error:', err.message);
    return res.status(500).json({ error: 'Internal server error.' });
  }
});

// ─── Health check (for deploy platforms) ─────────────────────────────────────
app.get('/health', (_req, res) => res.json({ status: 'ok', ts: Date.now() }));

// ─── SPA fallback ─────────────────────────────────────────────────────────────
app.get('/{*path}', (_req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// ─── Start ────────────────────────────────────────────────────────────────────
app.listen(PORT, () => {
  console.log(`[server] Running on http://localhost:${PORT}`);
  console.log(`[server] Gemini API key loaded: ${process.env.GEMINI_API_KEY ? '✓' : '✗ MISSING'}`);
});
